import { Container } from "@mui/material";
import Head from "next/head";
import React, { ReactNode } from "react";
import Header from "./Header";

const index = (props: props) => {
  const title = props.title ? `${props.title} | My Wallet` : "My Wallet";
  return (
    <Container>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header address={props.address} />
      <main className="Content">{props.children}</main>
    </Container>
  );
};

type props = {
  address: [String, Function];
  title?: string;
  desc?: string;
  children: ReactNode;
};
export default index;
